metadata:
  type: /entity/v1/service
  id: /rvu/airship/logging
---
metadata:
  type: /relation/v1/is_part_of
properties:
  a: /rvu/airship/logging
  b: /rvu/airship
---
metadata:
  type: /relation/v1/is_classified_as
properties:
  a: /rvu/airship/logging
  b: /classification/restricted
